### ISSUE TITLE
Unify Uncertainty Baselines' and Robustness Metrics' dataset APIs

### ISSUE THREAD

**Issue by dustinvtran** [google/uncertainty-baselines#118]
We can seamlessly use the same API for either training in UB or evaluation in RM.

**Comment by znado** [comment]
We should also investigate merging the dataset APIs of the Visual Task Adaptation Benchmark (VTAB) https://github.com/google-research/task_adaptation/blob/master/task_adaptation/data/base.py

**Comment by dustinvtran** [comment]
Fixed in https://github.com/google/uncertainty-baselines/pull/236.
