### ISSUE TITLE
Dropout flags missing in SNGP

### ISSUE THREAD

**Issue by y0ast** [google/uncertainty-baselines#140]
Hi,

When adding the augmix to SNGP, it seems some flags were erroneously deleted:

https://github.com/google/uncertainty-baselines/commit/8acdeb88ae0ffd48a8c27071dae6a7260ffcf1a9#diff-c81590c5b490d908013635ffcd33d867L92

the code fails to run without them.

**Comment by dustinvtran** [comment]
@ywen666 @jereliu

**Comment by jereliu** [comment]
@y0ast Thanks for reporting Joost! [They are recovered](https://github.com/google/uncertainty-baselines/blob/539571c8fbda786023987f3bd502d9fbbd9e0511/baselines/cifar/sngp.py#L118) in the latest commit.

**Comment by y0ast** [comment]
Thanks! :)
