### ISSUE TITLE
Where is the uncertainty-metrics repository?

### ISSUE THREAD

**Issue by mephody-bro** [google/uncertainty-baselines#317]
To reproduce the experiments we need the [uncertainty-metrics repository](https://github.com/google/uncertainty-metrics). It's mentioned in extras_require and could be found in google search cache, but it's not available at the moment - it seems it has been made private or has been moved. How can I install this dependency?

**Comment by patienceFromZhou** [comment]
pip3 install uncertainty_metrics

**Comment by patienceFromZhou** [comment]
perhaps you should  encountered with another import error "robustness_metrics", fix it by pip install "git+https://github.com/google-research/robustness_metrics.git#egg=robustness_metrics".
however i think we need a more friendly user guide, to make this repo "easily forkable" @znado

**Comment by znado** [comment]
Sorry about this! We're actively merging the uncertainty-metrics repo into [Robustness Metrics](https://github.com/google-research/robustness_metrics), which will fix these dependency issues. Pip installing uncertainty_metrics (not from github) will continue to work, but we won't be maintaining it.

**Comment by mephody-bro** [comment]
Ok, I got it, thanks for you reply
