### ISSUE TITLE
Issue with Dependencies and Colab 

### ISSUE THREAD

**Issue by tomersein** [google/uncertainty-baselines#407]
Hello,
I'm trying to use the batch ensemble model with Colab.
I Tried to to pip install the repository, but it raises the below errors while downloading:

```
ERROR: tensorflow 2.5.0 has requirement keras-nightly~=2.5.0.dev, but you'll have keras-nightly 2.7.0.dev2021070800 which is incompatible.
ERROR: tf-nightly 2.7.0.dev20210708 has requirement grpcio<2.0,>=1.37.0, but you'll have grpcio 1.34.1 which is incompatible.
```

When I try to import uncertainty_baselines I get this error:

`ImportError: cannot import name '__version__' from 'keras' (/usr/local/lib/python3.7/dist-packages/keras/__init__.py)
`

**I've tried to fix the versions as below:**
```
!pip install keras-nightly==2.5.0.dev2021020510
!pip install grpcio==1.34.0
!pip install tensorflow==2.5.0
!pip install tf-nightly==2.7.0.dev20210708
```

**and after that:**
`!pip install "git+https://github.com/google/uncertainty-baselines.git#egg=uncertainty_baselines"
`

but it didn't work.

Is it possible to specify what versions can solve this dependencies issue? 

**Edition:**

My main target is to able to run the batch ensemble model. I've seen an older thread which mentioned this pip install:
`!pip install "git+https://github.com/google/uncertainty-baselines.git#egg=uncertainty_baselines[models]"`

it doesn't raise any error (only warning):

```
WARNING:absl:Submodule datasets was found, but will not be loaded due to AttributeError within it while importing.
/usr/local/lib/python3.7/dist-packages/edward2/__init__.py:34: UserWarning: JAX backend for Edward2 is not available.
  warnings.warn("JAX backend for Edward2 is not available.")
WARNING:absl:Submodule models was found, but will not be loaded due to AttributeError within it while importing.
/usr/local/lib/python3.7/dist-packages/tensorflow_addons/utils/ensure_tf_install.py:43: UserWarning: You are currently using a nightly version of TensorFlow (2.6.0-dev20210501). 
TensorFlow Addons offers no support for the nightly versions of TensorFlow. Some things might work, some other might not. 
If you encounter a bug, do not file an issue on GitHub.
  UserWarning,
```

but when I try to build the model with this part of code:
```
import uncertainty_baselines as ub

model = ub.models.wide_resnet(input_shape=(32, 32, 3),
                              depth=28,
                              width_multiplier=10,
                              num_classes=10,
                              l2=1e-4)
```

this error occurs:
`AttributeError: module 'uncertainty_baselines' has no attribute 'models'`

Thanks a lot!

**Comment by kpzc7wl** [comment]
I finally got batchensemble running by removing most xxx-nightly packages (also comment out modules not needed, e.g., vit-transformer models). There's too much compatibility issue and also cuda errors. It seems to me the solution is to avoid xxx-nightly as much as possible.

**Comment by dustinvtran** [comment]
Thanks for raising this issue. To accommodate the weird versioning with nightly, I removed the specific dependence: https://github.com/google/uncertainty-baselines/pull/530
