### ISSUE TITLE
ImportError: cannot import name 'Cifar10HDataset'

### ISSUE THREAD

**Issue by ItamarKanter** [google/uncertainty-baselines#415]
I have installed uncertanity-baselines but failed to load it due to the following error:
```
import uncertainty_baselines as ub
ImportError: cannot import name 'Cifar10HDataset'
```
Has anyone experienced a similar issue or have an idea how to solve it?

**Comment by thlarsen13** [comment]
I am experiencing the same issue, and I will post here if I find a solution.

**Comment by thlarsen13** [comment]
It seems that there is ongoing development which appears to have broken part of the code. I didn't understand the changes that are causing it to break, so I recommend just working with an earlier version of the code. This commit from 9 days ago appears to work: 2da91af.

**Comment by znado** [comment]
We will look into this and fix it ASAP!

**Comment by znado** [comment]
Let me know if [this PR](https://github.com/google/uncertainty-baselines/pull/435) did not fix the problem!
