### ISSUE TITLE
Example code for computing Mahalanobis score in TF-2 

### ISSUE THREAD

**Issue by aqibsaeed** [google/uncertainty-baselines#775]
Hi, Is there an example code (or colab) to compute Mahalanobis score as presented in the following paper: `A Simple Fix to Mahalanobis Distance for Improving Near-OOD Detection`?

Thanks.

**Comment by dustinvtran** [comment]
cc @jessieren

**Comment by aqibsaeed** [comment]
@jessieren any update on this? Thanks in advance.

**Comment by jessieren** [comment]
Hi @aqibsaeed, so sorry for my late response. You can find the related code at https://github.com/google/uncertainty-baselines/blob/main/experimental/near_ood/vit/ood_utils.py

search for 'Relative Mahalanobis' and 'rmaha'.

Hope that helps!
